'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace kerametal

    Partial Public Class active_guests
        Inherits XPLiteObject
        Dim fip As String
        <Key()>
        <Size(15)>
        Public Property ip() As String
            Get
                Return fip
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ip", fip, value)
            End Set
        End Property
        Dim ftimestamp As UInteger
        Public Property timestamp() As UInteger
            Get
                Return ftimestamp
            End Get
            Set(ByVal value As UInteger)
                SetPropertyValue(Of UInteger)("timestamp", ftimestamp, value)
            End Set
        End Property
    End Class

End Namespace
