'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class artikli
    Public Property an As Integer
    Public Property tip As Nullable(Of Integer)
    Public Property sifra As String
    Public Property objekt As String
    Public Property naziv As String
    Public Property jed As String
    Public Property ozn As String
    Public Property grupa As String
    Public Property proiz As String
    Public Property tarifa As String
    Public Property nc As Nullable(Of Double)
    Public Property vpc As Nullable(Of Double)
    Public Property mpc As Nullable(Of Double)
    Public Property elekt_razred As String
    Public Property elekt_podrazred As String
    Public Property tezina As Nullable(Of Double)
    Public Property tar_broj As String
    Public Property stopa As Nullable(Of Double)
    Public Property id As Nullable(Of Integer)
    Public Property datum As Nullable(Of Date)
    Public Property plu As Nullable(Of Double)
    Public Property dok As String
    Public Property pc As Nullable(Of Double)
    Public Property placanje As Nullable(Of Integer)

End Class
