'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dok_sta_d
    Public Property tip As Nullable(Of Integer)
    Public Property broj As Nullable(Of Integer)
    Public Property god As Nullable(Of Integer)
    Public Property sifra As String
    Public Property objekt As String
    Public Property kasa As Nullable(Of Integer)
    Public Property naziv As String
    Public Property jedinica As String
    Public Property kolicina As Nullable(Of Double)
    Public Property mpc As Nullable(Of Double)
    Public Property pc As Nullable(Of Double)
    Public Property rabat As Nullable(Of Double)
    Public Property iznos As Nullable(Of Double)
    Public Property rabat1 As Nullable(Of Double)
    Public Property rabat2 As Nullable(Of Double)
    Public Property sconto As Nullable(Of Double)
    Public Property pg As String
    Public Property stopa As Nullable(Of Double)
    Public Property vpc As Nullable(Of Double)
    Public Property dat As Nullable(Of Date)
    Public Property cd As Nullable(Of Double)
    Public Property zt As Nullable(Of Double)
    Public Property zt_a As Nullable(Of Double)
    Public Property ca As Nullable(Of Double)
    Public Property ca_a As Nullable(Of Double)
    Public Property tr As Nullable(Of Double)
    Public Property nc As Nullable(Of Double)
    Public Property vpm As Nullable(Of Double)
    Public Property mpm As Nullable(Of Double)
    Public Property pdv As Nullable(Of Double)
    Public Property dec As Nullable(Of Integer)
    Public Property an As Integer
    Public Property vpc1 As Nullable(Of Double)
    Public Property vprab As Nullable(Of Double)
    Public Property prodaja As Nullable(Of Integer)
    Public Property profaktura As Nullable(Of Integer)
    Public Property faktura As Nullable(Of Integer)
    Public Property revers As Nullable(Of Integer)
    Public Property dat_dok As Nullable(Of Date)
    Public Property zak_brojila As Nullable(Of Integer)
    Public Property vozilo As String
    Public Property vozac As String
    Public Property plu As Nullable(Of Double)
    Public Property dat_print As Nullable(Of Date)

End Class
