'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class partneri
    Public Property sifra As Integer
    Public Property objekt As String
    Public Property Naziv As String
    Public Property Mjesto As String
    Public Property Adresa As String
    Public Property Inozemni As Nullable(Of Integer)
    Public Property Entitet As Nullable(Of Integer)
    Public Property Maticni As String
    Public Property Obveznik As Nullable(Of Integer)
    Public Property PB As String
    Public Property E_mail As String
    Public Property Telefon As String
    Public Property Kontakt As String
    Public Property referent As Nullable(Of Integer)
    Public Property sifra1 As Nullable(Of Integer)
    Public Property opis As String
    Public Property nije_fakt As Nullable(Of Double)
    Public Property dani As Nullable(Of Integer)
    Public Property limit As Nullable(Of Double)
    Public Property interno As Nullable(Of Integer)

End Class
