'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class users
    Public Property username As String
    Public Property password As String
    Public Property usersalt As String
    Public Property userid As String
    Public Property userlevel As Boolean
    Public Property email As String
    Public Property timestamp As Long
    Public Property actkey As String
    Public Property ip As String
    Public Property regdate As Long

End Class
